pull_request_rules:
  - name: high priority merge of hotfix branches
    conditions:
      - "check-success=ci/circleci: build-and-test"
      - base=main
      - label=hotfix
    actions:
      merge:
        method: rebase
        strict: smart
        strict_method: rebase
        priority: high
      label:
        remove: [on-merge-queue,ready-for-review]
        
  - name: regular priority branch
    conditions:
      - "check-success=ci/circleci: build-and-test"
      - base=main
      - label=on-merge-queue
    actions:
      merge:
        method: rebase
        strict: smart
        strict_method: rebase
        priority: medium
      label:
        remove: [on-merge-queue,ready-for-review]


  - name: remove on-merge-queue label after failure
    conditions:
      - "check-success!=ci/circleci: build-and-test"
      - base=main
      - label=on-merge-queue
    actions:
      label:
        remove: [on-merge-queue,ready-for-review]
        add: [work-in-progress]
